### ISSUE TITLE
[epic] Reach first useable stage

### ISSUE THREAD

**Issue by perillamint** [perillamint/musubi#2]
Things to do:

* [ ] Implement account sign-in and management API
* [ ] Implement key management
* [ ] Implement Wireguard driver
